//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v12.0.0+ba724ed
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>AS - Search Settings</summary>
	[PublishedModel("searchSettings")]
	public partial class SearchSettings : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		public new const string ModelTypeAlias = "searchSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<SearchSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public SearchSettings(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Convert To WebP
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[ImplementPropertyType("apiResultConvertToWebP")]
		public virtual bool ApiResultConvertToWebP => this.Value<bool>(_publishedValueFallback, "apiResultConvertToWebP");

		///<summary>
		/// Image Field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("apiResultImage")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ApiResultImage => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "apiResultImage");

		///<summary>
		/// Image Crop: If you want to use an Image Crop set here its alias.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("apiResultImageCrop")]
		public virtual string ApiResultImageCrop => this.Value<string>(_publishedValueFallback, "apiResultImageCrop");

		///<summary>
		/// Image Quality: 50% - 99%. By default it is 95%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[ImplementPropertyType("apiResultImageQuality")]
		public virtual int ApiResultImageQuality => this.Value<int>(_publishedValueFallback, "apiResultImageQuality");

		///<summary>
		/// Release Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("apiResultReleaseDate")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ApiResultReleaseDate => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "apiResultReleaseDate");

		///<summary>
		/// Text Field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("apiResultText")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ApiResultText => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "apiResultText");

		///<summary>
		/// Text Max Length
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[ImplementPropertyType("apiResultTextMaxLength")]
		public virtual int ApiResultTextMaxLength => this.Value<int>(_publishedValueFallback, "apiResultTextMaxLength");

		///<summary>
		/// Title Field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("apiResultTitle")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ApiResultTitle => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "apiResultTitle");

		///<summary>
		/// Title Max Length
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[ImplementPropertyType("apiResultTitleMaxLength")]
		public virtual int ApiResultTitleMaxLength => this.Value<int>(_publishedValueFallback, "apiResultTitleMaxLength");

		///<summary>
		/// Release Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("computedReleaseDate")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ComputedReleaseDate => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "computedReleaseDate");

		///<summary>
		/// Text Fields
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("computedText")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ComputedText => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "computedText");

		///<summary>
		/// Title Fields
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("computedTitle")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ComputedTitle => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "computedTitle");

		///<summary>
		/// Title Boost
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[ImplementPropertyType("computedTitleBoost")]
		public virtual decimal ComputedTitleBoost => this.Value<decimal>(_publishedValueFallback, "computedTitleBoost");

		///<summary>
		/// Aliases: Add here the aliases of the document types that you want to be excluded from the search
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.0+ba724ed")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("excludedDocumentTypesAliases")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ExcludedDocumentTypesAliases => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "excludedDocumentTypesAliases");
	}
}
